'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Peppertree.Solutions.NuTask

    Partial Public Class frmExpense

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxPanel

        '''<summary>
        '''pnlError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlSelectProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSelectProject As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSelectProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectProject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpProjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpProjects As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''pnlSelectTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSelectTask As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSelectTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectTask As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpTasks As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''lblExpenseText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpenseText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtExpenseText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpenseText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblExpenseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpenseDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlExpenseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlExpenseDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''lblExpenseCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpenseCategory As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpExpenseCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpExpenseCategory As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''lblExpenseAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpenseAmount As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtExpenseAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpenseAmount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblExpenseReceiptNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpenseReceiptNumber As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtExpenseReceiptNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpenseReceiptNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlExpenseFormActions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlExpenseFormActions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCancel As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ctlLoading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlLoading As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxLoadingPanel
    End Class
End Namespace
