'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Peppertree.Solutions.NuTask

    Partial Public Class frmNote

        '''<summary>
        '''ctlScripts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlScripts As Global.DotNetNuke.Web.UI.WebControls.DnnScriptBlock

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxPanel

        '''<summary>
        '''pnlError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlSelectProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSelectProject As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSelectProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectProject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpProjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpProjects As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''pnlSelectTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSelectTask As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSelectTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectTask As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpTasks As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''lblNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNote As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNote As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdAddNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddNote As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCancel As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ctlLoading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlLoading As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxLoadingPanel
    End Class
End Namespace
