'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Peppertree.Solutions.NuTask

    Partial Public Class frmTask

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxPanel

        '''<summary>
        '''tabBasicValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabBasicValues As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''tabFinacialValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabFinacialValues As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''tabTimingValues control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabTimingValues As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTaskName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTaskName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTaskName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTaskDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskDescription As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTaskDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTaskDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProject As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpProjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpProjects As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''lblCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategory As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCategories As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpStatus As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''lblAssignedTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAssignedTo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpUsers As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''lblAllocatedBudget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllocatedBudget As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAllocatedBudget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllocatedBudget As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAllocatedExpenses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllocatedExpenses As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAllocatedExpenses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllocatedExpenses As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblDueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDueDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlDueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDueDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''lblStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlStartDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''lblEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlEndDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''lblEstimatedTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEstimatedTime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEstimatedTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEstimatedTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEstimatedTimeUnit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEstimatedTimeUnit As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpEstimatedTimeUnit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpEstimatedTimeUnit As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''pnlTaskFormActions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTaskFormActions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdUpdateTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateTask As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDeleteTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteTask As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCancelEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCancelEdit As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ctlLoading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlLoading As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxLoadingPanel
    End Class
End Namespace
