'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Peppertree.Solutions.NuTask

    Partial Public Class List_Tasks

        '''<summary>
        '''ctlScripts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlScripts As Global.DotNetNuke.Web.UI.WebControls.DnnScriptBlock

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxPanel

        '''<summary>
        '''pnlProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProject As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblProjectTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblProjectDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblProjectDueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectDueDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblProjectDueDateValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectDueDateValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectBudget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectBudget As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblProjectBudgetValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectBudgetValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTaskBudget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskBudget As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTaskBudgetValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskBudgetValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkProjectExpenses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkProjectExpenses As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblProjectExpensesValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectExpensesValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkTaskExpenses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkTaskExpenses As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblTaskExpensesValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskExpensesValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkExpensesAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkExpensesAll As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblExpensesAllValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpensesAllValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBalance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBalance As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblBalanceValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBalanceValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlTaskGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTaskGrid As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdTasks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdTasks As Global.DotNetNuke.Web.UI.WebControls.DnnGrid

        '''<summary>
        '''pnlGridActions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlGridActions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lnkAddTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAddTask As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkAddNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAddNote As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkAddExpense control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAddExpense As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''ctlLoading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlLoading As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxLoadingPanel
    End Class
End Namespace
