'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Peppertree.Solutions.NuTask

    Partial Public Class vwTask

        '''<summary>
        '''ctlAjax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAjax As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxPanel

        '''<summary>
        '''lblTaskValue_Title control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_Title As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlTaskView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTaskView As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''tabTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabTask As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''tabExpenses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabExpenses As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTaskValue_Description control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_Description As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_Notes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_Notes As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rptNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptNotes As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''grdTaskExpenses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdTaskExpenses As Global.DotNetNuke.Web.UI.WebControls.DnnGrid

        '''<summary>
        '''lblExpenseTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpenseTotal As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTaskExpenseTotalValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskExpenseTotalValue As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_Category control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_Category As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_Category control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_Category As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_Status control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_Status As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_Status control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_Status As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_AmountAllowance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_AmountAllowance As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_AmountAllowance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_AmountAllowance As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_AmountSpent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_AmountSpent As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_AmountSpent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_AmountSpent As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_EstimatedTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_EstimatedTime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_EstimatedTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_EstimatedTime As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_DueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_DueDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_DueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_DueDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_StartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_StartDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_StartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_StartDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_EndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_EndDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_EndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_EndDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_AssignedTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_AssignedTo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_AssignedTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_AssignedTo As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_AssignedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_AssignedDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_AssignedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_AssignedDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_CreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_CreatedBy As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_CreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_CreatedBy As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblViewTask_CreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewTask_CreatedDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblTaskValue_CreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTaskValue_CreatedDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lnkAddExpense control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAddExpense As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkAddNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkAddNote As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnkEditTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkEditTask As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''cmdDeleteTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteTask As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCancel As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''pnlTaskForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTaskForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ctlLoading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlLoading As Global.DotNetNuke.Web.UI.WebControls.DnnAjaxLoadingPanel
    End Class
End Namespace
